package dev.brewkits.kmpworkmanager

import dev.brewkits.kmpworkmanager.background.data.IosWorkerFactory
import dev.brewkits.kmpworkmanager.background.data.InfoPlistReader
import dev.brewkits.kmpworkmanager.background.data.NativeTaskScheduler
import dev.brewkits.kmpworkmanager.background.domain.BackgroundTaskScheduler
import dev.brewkits.kmpworkmanager.background.domain.BgTaskIdProvider
import dev.brewkits.kmpworkmanager.background.domain.TaskEventManager
import dev.brewkits.kmpworkmanager.background.domain.WorkerFactory
import dev.brewkits.kmpworkmanager.persistence.EventStore
import dev.brewkits.kmpworkmanager.persistence.ExecutionHistoryStore
import dev.brewkits.kmpworkmanager.persistence.IosEventStore
import dev.brewkits.kmpworkmanager.persistence.IosExecutionHistoryStore
import dev.brewkits.kmpworkmanager.utils.Logger
import org.koin.dsl.module

/**
 * iOS implementation of the Koin module.
 *
 * Breaking Change: Now requires WorkerFactory parameter
 * New: Optional config parameter for logging configuration
 *
 * **BGTask ID validation (automatic with KSP):**
 * When [workerFactory] implements [BgTaskIdProvider] (generated by `kmpworker-ksp`),
 * this module validates that all declared BGTask IDs are present in
 * `Info.plist → BGTaskSchedulerPermittedIdentifiers` at startup — failing fast with a
 * descriptive error rather than silently misbehaving at runtime.
 *
 * ```kotlin
 * // With KSP — validation is automatic:
 * kmpWorkerModule(workerFactory = IosWorkerFactoryGenerated())
 *
 * // Without KSP — pass IDs explicitly:
 * kmpWorkerModule(
 *     workerFactory = MyWorkerFactory(),
 *     iosTaskIds = setOf("com.example.sync-task")
 * )
 * ```
 *
 * @param workerFactory User-provided factory implementing IosWorkerFactory
 * @param config Configuration for logging and other settings
 * @param iosTaskIds Additional iOS task IDs (optional, Info.plist is primary source)
 */
actual fun kmpWorkerModule(
    workerFactory: WorkerFactory,
    config: KmpWorkManagerConfig,
    iosTaskIds: Set<String>
) = module {
    // Initialize logger with config
    Logger.setMinLevel(config.logLevel)
    config.customLogger?.let { Logger.setCustomLogger(it) }

    // Propagate runtime-accessible config (telemetry, battery guard, etc.)
    KmpWorkManagerRuntime.configure(config)

    // Validate factory type early (fail-fast on iOS)
    require(workerFactory is IosWorkerFactory) {
        """
        ❌ Invalid WorkerFactory for iOS platform

        Expected: IosWorkerFactory
        Received: ${workerFactory::class.qualifiedName}

        Solution:
        Create a factory implementing IosWorkerFactory on iOS:

        class MyWorkerFactory : IosWorkerFactory {
            override fun createWorker(workerClassName: String): IosWorker? {
                return when (workerClassName) {
                    "SyncWorker" -> SyncWorker()
                    else -> null
                }
            }
        }

        Then pass it to kmpWorkerModule:
        kmpWorkerModule(workerFactory = MyWorkerFactory())
        """.trimIndent()
    }

    // KSP BGTask ID validation: when the factory implements BgTaskIdProvider,
    // cross-check its declared IDs against Info.plist. Fail fast at startup so
    // developers discover misconfiguration immediately, not at background-task time.
    if (workerFactory is BgTaskIdProvider) {
        val permittedIds = InfoPlistReader.readPermittedTaskIds()
        val missing = workerFactory.requiredBgTaskIds - permittedIds
        require(missing.isEmpty()) {
            """
            ❌ Missing BGTask IDs in Info.plist

            The following IDs are declared via @Worker(bgTaskId = ...) but are absent
            from BGTaskSchedulerPermittedIdentifiers in Info.plist:

            ${missing.joinToString("\n") { "  • $it" }}

            Fix: add them to your Info.plist:
            <key>BGTaskSchedulerPermittedIdentifiers</key>
            <array>
            ${missing.joinToString("\n") { "    <string>$it</string>" }}
                <!-- ...existing IDs... -->
            </array>
            """.trimIndent()
        }
    }

    single<BackgroundTaskScheduler> {
        NativeTaskScheduler(
            additionalPermittedTaskIds = iosTaskIds,
            diskSpaceBufferBytes = config.minFreeDiskSpaceBytes
        )
    }

    // Register the user's worker factory (already validated above)
    single<WorkerFactory> { workerFactory }
    single<IosWorkerFactory> { workerFactory }

    // Event persistence
    single<EventStore> {
        val store = IosEventStore()
        TaskEventManager.initialize(store)
        store
    }

    // Execution history persistence
    single<ExecutionHistoryStore> {
        IosExecutionHistoryStore().also { KmpWorkManagerRuntime.setHistoryStore(it) }
    }
}
